#!/bin/bash

files=(.vim .vimrc .gitconfig .zshrc .irssi .ssh/config .ssh/authorized_keys .tmux.conf)
files_len=${#files[*]}

# For each file in the file list
for ((i=0; i<files_len; i++)); do

	# If file already exists
	if [[ -h "$HOME/${files[i]}" || -e "$HOME/${files[i]}" ]]; then

		# Prompt to delete it
		while true; do
			read -p "Do you wish to remove $HOME/${files[i]}? "
			case $REPLY in
				[Yy]* ) rm -rf "$HOME/${files[i]}"; break;;
				[Nn]* ) continue 2;;
				* ) echo "Please answer yes or no.";;
			esac
		done
	fi

	# Create a symlink
	echo "ln -s $PWD/${files[i]} $HOME/${files[i]}"
	ln -s "$PWD/${files[i]}" "$HOME/${files[i]}"
done

# Install required software
if [[ -e '/usr/bin/apt-get' ]]; then
	sudo apt-get install git tmux zsh vim vim-youcompleteme exuberant-ctags
fi
if [[ -e '/usr/bin/pacman' ]]; then
	sudo pacman --sync --needed git tmux zsh vim
fi

# Update shell
chsh -s /bin/zsh
