#!/bin/bash

files=(.vim .vimrc .bashrc .bash_aliases)
files_len=${#files[*]}

for ((i=0; i<files_len; i++)); do
	if [[ -e "$HOME/${files[i]}" ]]; then
		rm -ri "$HOME/${files[i]}"
	fi
	echo "Creating ${files[i]}..."
	ln -s "$PWD/${files[i]}" "$HOME/${files[i]}"
done

echo 'Done.'
